In [2]:
 # import dependencies 
import os
import pandas as pd

In [5]:
 # generate path to csv
csv_path = os.path.join('assets/data', 'CityWeatherData.csv')
cities_csv = pd.read_csv(csv_path)
cities_csv

,City,Country,Latitude,Longitude,Date,Wind_Speed,Humidity,Max_Temp,Cloudiness
0,Arraial do Cabo,BR,-22.9661,-42.0278,1.646991e+09,19.57,88.0,75.06,0.0
1,Boa Vista,BR,2.8197,-60.6733,1.646990e+09,4.61,78.0,76.98,40.0
2,Torbay,CA,47.6666,-52.7314,1.646991e+09,20.71,89.0,29.75,40.0
3,Gornyy,RU,55.1153,83.9059,1.646991e+09,9.13,80.0,4.17,57.0
4,Chui,UY,-33.6971,-53.4616,1.646991e+09,7.34,73.0,58.10,69.0
...,...,...,...,...,...,...,...,...,...
557,Warwick,US,41.7001,-71.4162,1.646991e+09,0.00,90.0,37.33,0.0
558,Manuk Mangkaw,PH,4.8000,119.8500,1.646991e+09,8.39,74.0,83.16,80.0
559,Guane,CU,22.2025,-84.0875,1.646991e+09,5.50,92.0,72.45,5.0
560,Dakoro,NE,14.5106,6.7650,1.646991e+09,15.52,13.0,87.96,100.0
561,Asheville,US,35.6009,-82.5540,1.646991e+09,4.00,90.0,43.97,100.0

In [6]:
# create html table and save to file 
cities_csv.to_html('table.html', index=False, classes=['table', 'table-striped', 'table-hover'])